/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import type {
  AuthResponseDto,
  CreateEventMapDto,
  CreateMessageDto,
  CreateSessionDto,
  EventMapResponseDto,
  LoginDto,
  MessageDto,
  MessagesControllerGetMessagesParams,
  MessagesResponseDto,
  PurchaseSubscriptionDto,
  RefreshTokenDto,
  RegisterDto,
  SessionResponseDto,
  SubscriptionResponseDto,
  TelegramLinkDto,
  TelegramLoginDto,
  UserProfileDto
} from './schemas';

import { axiosInstance } from './mutator';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSeeeApi = () => {
/**
 * @summary Вход по email и паролю
 */
const authControllerLogin = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof axiosInstance<AuthResponseDto>>,) => {
      return axiosInstance<AuthResponseDto>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      options);
    }
  
/**
 * @summary Регистрация нового пользователя
 */
const authControllerRegister = (
    registerDto: RegisterDto,
 options?: SecondParameter<typeof axiosInstance<AuthResponseDto>>,) => {
      return axiosInstance<AuthResponseDto>(
      {url: `/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      options);
    }
  
/**
 * @summary Вход через Telegram Login Widget
 */
const authControllerLoginWithTelegram = (
    telegramLoginDto: TelegramLoginDto,
 options?: SecondParameter<typeof axiosInstance<AuthResponseDto>>,) => {
      return axiosInstance<AuthResponseDto>(
      {url: `/api/v1/auth/telegram/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: telegramLoginDto
    },
      options);
    }
  
/**
 * @summary Привязать Telegram аккаунт к текущему пользователю
 */
const authControllerLinkTelegram = (
    telegramLinkDto: TelegramLinkDto,
 options?: SecondParameter<typeof axiosInstance<UserProfileDto>>,) => {
      return axiosInstance<UserProfileDto>(
      {url: `/api/v1/auth/telegram/link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: telegramLinkDto
    },
      options);
    }
  
/**
 * @summary Обновление токенов
 */
const authControllerRefresh = (
    refreshTokenDto: RefreshTokenDto,
 options?: SecondParameter<typeof axiosInstance<AuthResponseDto>>,) => {
      return axiosInstance<AuthResponseDto>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenDto
    },
      options);
    }
  
/**
 * @summary Получить данные текущего пользователя
 */
const authControllerGetMe = (
    
 options?: SecondParameter<typeof axiosInstance<UserProfileDto>>,) => {
      return axiosInstance<UserProfileDto>(
      {url: `/api/v1/auth/me`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Создать новую сессию
 */
const sessionsControllerCreateSession = (
    createSessionDto: CreateSessionDto,
 options?: SecondParameter<typeof axiosInstance<SessionResponseDto>>,) => {
      return axiosInstance<SessionResponseDto>(
      {url: `/api/v1/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSessionDto
    },
      options);
    }
  
/**
 * @summary Получить все сессии пользователя
 */
const sessionsControllerGetSessions = (
    
 options?: SecondParameter<typeof axiosInstance<SessionResponseDto[]>>,) => {
      return axiosInstance<SessionResponseDto[]>(
      {url: `/api/v1/sessions`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Получить сессию по ID
 */
const sessionsControllerGetSession = (
    id: string,
 options?: SecondParameter<typeof axiosInstance<SessionResponseDto>>,) => {
      return axiosInstance<SessionResponseDto>(
      {url: `/api/v1/sessions/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Скачать документ сессии (Markdown)
 */
const sessionsControllerGetDocument = (
    id: string,
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/sessions/${id}/document`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Добавить сессию в нейрокарту
 */
const sessionsControllerAddSessionToMap = (
    id: string,
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/sessions/${id}/add-to-map`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Получить текущую подписку пользователя
 */
const subscriptionControllerGetSubscription = (
    
 options?: SecondParameter<typeof axiosInstance<SubscriptionResponseDto>>,) => {
      return axiosInstance<SubscriptionResponseDto>(
      {url: `/api/v1/subscription`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Оформить подписку
 */
const subscriptionControllerPurchase = (
    purchaseSubscriptionDto: PurchaseSubscriptionDto,
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/subscription/purchase`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: purchaseSubscriptionDto
    },
      options);
    }
  
/**
 * @summary Подтвердить оплату (webhook от Lava)
 */
const subscriptionControllerConfirmPayment = (
    
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/subscription/confirm-payment`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Отменить подписку
 */
const subscriptionControllerCancel = (
    
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/subscription/cancel`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Проверить промокод
 */
const subscriptionControllerValidatePromo = (
    
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/subscription/validate-promo`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Webhook для уведомлений от Lava API
 */
const subscriptionControllerHandleLavaWebhook = (
    
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/subscription/webhook/lava`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Получить список доступных программ психолога
 */
const psychologistControllerListPrograms = (
    
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/psychologist/programs`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Получить программу по имени
 */
const psychologistControllerGetProgram = (
    programName: string,
 options?: SecondParameter<typeof axiosInstance<void>>,) => {
      return axiosInstance<void>(
      {url: `/api/v1/psychologist/programs/${programName}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Получить сообщения сессии с cursor pagination
 */
const messagesControllerGetMessages = (
    sessionId: string,
    params?: MessagesControllerGetMessagesParams,
 options?: SecondParameter<typeof axiosInstance<MessagesResponseDto>>,) => {
      return axiosInstance<MessagesResponseDto>(
      {url: `/api/v1/sessions/${sessionId}/messages`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Отправить сообщение в сессию
 */
const messagesControllerCreateMessage = (
    sessionId: string,
    createMessageDto: CreateMessageDto,
 options?: SecondParameter<typeof axiosInstance<MessageDto>>,) => {
      return axiosInstance<MessageDto>(
      {url: `/api/v1/sessions/${sessionId}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMessageDto
    },
      options);
    }
  
/**
 * @summary Получить все записи нейрокарты пользователя
 */
const eventMapControllerGetEventMap = (
    
 options?: SecondParameter<typeof axiosInstance<EventMapResponseDto[]>>,) => {
      return axiosInstance<EventMapResponseDto[]>(
      {url: `/api/v1/event-map`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Создать запись в нейрокарте
 */
const eventMapControllerCreateEventMap = (
    createEventMapDto: CreateEventMapDto,
 options?: SecondParameter<typeof axiosInstance<EventMapResponseDto>>,) => {
      return axiosInstance<EventMapResponseDto>(
      {url: `/api/v1/event-map`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventMapDto
    },
      options);
    }
  
return {authControllerLogin,authControllerRegister,authControllerLoginWithTelegram,authControllerLinkTelegram,authControllerRefresh,authControllerGetMe,sessionsControllerCreateSession,sessionsControllerGetSessions,sessionsControllerGetSession,sessionsControllerGetDocument,sessionsControllerAddSessionToMap,subscriptionControllerGetSubscription,subscriptionControllerPurchase,subscriptionControllerConfirmPayment,subscriptionControllerCancel,subscriptionControllerValidatePromo,subscriptionControllerHandleLavaWebhook,psychologistControllerListPrograms,psychologistControllerGetProgram,messagesControllerGetMessages,messagesControllerCreateMessage,eventMapControllerGetEventMap,eventMapControllerCreateEventMap}};
export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerLogin']>>>
export type AuthControllerRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerRegister']>>>
export type AuthControllerLoginWithTelegramResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerLoginWithTelegram']>>>
export type AuthControllerLinkTelegramResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerLinkTelegram']>>>
export type AuthControllerRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerRefresh']>>>
export type AuthControllerGetMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['authControllerGetMe']>>>
export type SessionsControllerCreateSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['sessionsControllerCreateSession']>>>
export type SessionsControllerGetSessionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['sessionsControllerGetSessions']>>>
export type SessionsControllerGetSessionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['sessionsControllerGetSession']>>>
export type SessionsControllerGetDocumentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['sessionsControllerGetDocument']>>>
export type SessionsControllerAddSessionToMapResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['sessionsControllerAddSessionToMap']>>>
export type SubscriptionControllerGetSubscriptionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerGetSubscription']>>>
export type SubscriptionControllerPurchaseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerPurchase']>>>
export type SubscriptionControllerConfirmPaymentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerConfirmPayment']>>>
export type SubscriptionControllerCancelResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerCancel']>>>
export type SubscriptionControllerValidatePromoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerValidatePromo']>>>
export type SubscriptionControllerHandleLavaWebhookResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['subscriptionControllerHandleLavaWebhook']>>>
export type PsychologistControllerListProgramsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['psychologistControllerListPrograms']>>>
export type PsychologistControllerGetProgramResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['psychologistControllerGetProgram']>>>
export type MessagesControllerGetMessagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['messagesControllerGetMessages']>>>
export type MessagesControllerCreateMessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['messagesControllerCreateMessage']>>>
export type EventMapControllerGetEventMapResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['eventMapControllerGetEventMap']>>>
export type EventMapControllerCreateEventMapResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSeeeApi>['eventMapControllerCreateEventMap']>>>
