/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AuthResponseDto,
  CreateEventMapDto,
  CreateMessageDto,
  CreateSessionDto,
  EventMapResponseDto,
  LoginDto,
  MessageDto,
  MessagesControllerGetMessagesParams,
  MessagesResponseDto,
  RefreshTokenDto,
  RegisterDto,
  SessionResponseDto,
  TelegramLinkDto,
  TelegramLoginDto,
  UserProfileDto
} from './schemas';

import { swrMutator } from './mutator';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  
/**
 * @summary Вход по email и паролю
 */
export const authControllerLogin = (
    loginDto: LoginDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<AuthResponseDto>(
    {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
    options);
  }



export const getAuthControllerLoginMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: LoginDto }) => {
    return authControllerLogin(arg, options);
  }
}
export const getAuthControllerLoginMutationKey = () => [`/api/v1/auth/login`] as const;

export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerLoginMutationError = void

/**
 * @summary Вход по email и паролю
 */
export const useAuthControllerLogin = <TError = void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof authControllerLogin>>, TError, Key, LoginDto, Awaited<ReturnType<typeof authControllerLogin>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLoginMutationKey();
  const swrFn = getAuthControllerLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Регистрация нового пользователя
 */
export const authControllerRegister = (
    registerDto: RegisterDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<AuthResponseDto>(
    {url: `/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
    options);
  }



export const getAuthControllerRegisterMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: RegisterDto }) => {
    return authControllerRegister(arg, options);
  }
}
export const getAuthControllerRegisterMutationKey = () => [`/api/v1/auth/register`] as const;

export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
export type AuthControllerRegisterMutationError = void

/**
 * @summary Регистрация нового пользователя
 */
export const useAuthControllerRegister = <TError = void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof authControllerRegister>>, TError, Key, RegisterDto, Awaited<ReturnType<typeof authControllerRegister>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthControllerRegisterMutationKey();
  const swrFn = getAuthControllerRegisterMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Вход через Telegram Login Widget
 */
export const authControllerLoginWithTelegram = (
    telegramLoginDto: TelegramLoginDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<AuthResponseDto>(
    {url: `/api/v1/auth/telegram/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: telegramLoginDto
    },
    options);
  }



export const getAuthControllerLoginWithTelegramMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: TelegramLoginDto }) => {
    return authControllerLoginWithTelegram(arg, options);
  }
}
export const getAuthControllerLoginWithTelegramMutationKey = () => [`/api/v1/auth/telegram/login`] as const;

export type AuthControllerLoginWithTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginWithTelegram>>>
export type AuthControllerLoginWithTelegramMutationError = void

/**
 * @summary Вход через Telegram Login Widget
 */
export const useAuthControllerLoginWithTelegram = <TError = void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof authControllerLoginWithTelegram>>, TError, Key, TelegramLoginDto, Awaited<ReturnType<typeof authControllerLoginWithTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLoginWithTelegramMutationKey();
  const swrFn = getAuthControllerLoginWithTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Привязать Telegram аккаунт к текущему пользователю
 */
export const authControllerLinkTelegram = (
    telegramLinkDto: TelegramLinkDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<UserProfileDto>(
    {url: `/api/v1/auth/telegram/link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: telegramLinkDto
    },
    options);
  }



export const getAuthControllerLinkTelegramMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: TelegramLinkDto }) => {
    return authControllerLinkTelegram(arg, options);
  }
}
export const getAuthControllerLinkTelegramMutationKey = () => [`/api/v1/auth/telegram/link`] as const;

export type AuthControllerLinkTelegramMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLinkTelegram>>>
export type AuthControllerLinkTelegramMutationError = void | void

/**
 * @summary Привязать Telegram аккаунт к текущему пользователю
 */
export const useAuthControllerLinkTelegram = <TError = void | void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof authControllerLinkTelegram>>, TError, Key, TelegramLinkDto, Awaited<ReturnType<typeof authControllerLinkTelegram>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthControllerLinkTelegramMutationKey();
  const swrFn = getAuthControllerLinkTelegramMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Обновление токенов
 */
export const authControllerRefresh = (
    refreshTokenDto: RefreshTokenDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<AuthResponseDto>(
    {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenDto
    },
    options);
  }



export const getAuthControllerRefreshMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: RefreshTokenDto }) => {
    return authControllerRefresh(arg, options);
  }
}
export const getAuthControllerRefreshMutationKey = () => [`/api/v1/auth/refresh`] as const;

export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>
export type AuthControllerRefreshMutationError = void

/**
 * @summary Обновление токенов
 */
export const useAuthControllerRefresh = <TError = void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof authControllerRefresh>>, TError, Key, RefreshTokenDto, Awaited<ReturnType<typeof authControllerRefresh>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAuthControllerRefreshMutationKey();
  const swrFn = getAuthControllerRefreshMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить данные текущего пользователя
 */
export const authControllerGetMe = (
    
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<UserProfileDto>(
    {url: `/api/v1/auth/me`, method: 'GET'
    },
    options);
  }



export const getAuthControllerGetMeKey = () => [`/api/v1/auth/me`] as const;

export type AuthControllerGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGetMe>>>
export type AuthControllerGetMeQueryError = void

/**
 * @summary Получить данные текущего пользователя
 */
export const useAuthControllerGetMe = <TError = void>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof authControllerGetMe>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAuthControllerGetMeKey() : null);
  const swrFn = () => authControllerGetMe(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Создать новую сессию
 */
export const sessionsControllerCreateSession = (
    createSessionDto: CreateSessionDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<SessionResponseDto>(
    {url: `/api/v1/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSessionDto
    },
    options);
  }



export const getSessionsControllerCreateSessionMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: CreateSessionDto }) => {
    return sessionsControllerCreateSession(arg, options);
  }
}
export const getSessionsControllerCreateSessionMutationKey = () => [`/api/v1/sessions`] as const;

export type SessionsControllerCreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof sessionsControllerCreateSession>>>
export type SessionsControllerCreateSessionMutationError = void | void

/**
 * @summary Создать новую сессию
 */
export const useSessionsControllerCreateSession = <TError = void | void>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof sessionsControllerCreateSession>>, TError, Key, CreateSessionDto, Awaited<ReturnType<typeof sessionsControllerCreateSession>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSessionsControllerCreateSessionMutationKey();
  const swrFn = getSessionsControllerCreateSessionMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить все сессии пользователя
 */
export const sessionsControllerGetSessions = (
    
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<SessionResponseDto[]>(
    {url: `/api/v1/sessions`, method: 'GET'
    },
    options);
  }



export const getSessionsControllerGetSessionsKey = () => [`/api/v1/sessions`] as const;

export type SessionsControllerGetSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof sessionsControllerGetSessions>>>
export type SessionsControllerGetSessionsQueryError = unknown

/**
 * @summary Получить все сессии пользователя
 */
export const useSessionsControllerGetSessions = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof sessionsControllerGetSessions>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getSessionsControllerGetSessionsKey() : null);
  const swrFn = () => sessionsControllerGetSessions(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить сессию по ID
 */
export const sessionsControllerGetSession = (
    id: string,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<SessionResponseDto>(
    {url: `/api/v1/sessions/${id}`, method: 'GET'
    },
    options);
  }



export const getSessionsControllerGetSessionKey = (id: string,) => [`/api/v1/sessions/${id}`] as const;

export type SessionsControllerGetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof sessionsControllerGetSession>>>
export type SessionsControllerGetSessionQueryError = void

/**
 * @summary Получить сессию по ID
 */
export const useSessionsControllerGetSession = <TError = void>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof sessionsControllerGetSession>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getSessionsControllerGetSessionKey(id) : null);
  const swrFn = () => sessionsControllerGetSession(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Скачать документ сессии (Markdown)
 */
export const sessionsControllerGetDocument = (
    id: string,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<void>(
    {url: `/api/v1/sessions/${id}/document`, method: 'GET'
    },
    options);
  }



export const getSessionsControllerGetDocumentKey = (id: string,) => [`/api/v1/sessions/${id}/document`] as const;

export type SessionsControllerGetDocumentQueryResult = NonNullable<Awaited<ReturnType<typeof sessionsControllerGetDocument>>>
export type SessionsControllerGetDocumentQueryError = void

/**
 * @summary Скачать документ сессии (Markdown)
 */
export const useSessionsControllerGetDocument = <TError = void>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof sessionsControllerGetDocument>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getSessionsControllerGetDocumentKey(id) : null);
  const swrFn = () => sessionsControllerGetDocument(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Добавить сессию в нейрокарту
 */
export const sessionsControllerAddSessionToMap = (
    id: string,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<void>(
    {url: `/api/v1/sessions/${id}/add-to-map`, method: 'POST'
    },
    options);
  }



export const getSessionsControllerAddSessionToMapMutationFetcher = (id: string, options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, __: { arg: Arguments }) => {
    return sessionsControllerAddSessionToMap(id, options);
  }
}
export const getSessionsControllerAddSessionToMapMutationKey = (id: string,) => [`/api/v1/sessions/${id}/add-to-map`] as const;

export type SessionsControllerAddSessionToMapMutationResult = NonNullable<Awaited<ReturnType<typeof sessionsControllerAddSessionToMap>>>
export type SessionsControllerAddSessionToMapMutationError = unknown

/**
 * @summary Добавить сессию в нейрокарту
 */
export const useSessionsControllerAddSessionToMap = <TError = unknown>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof sessionsControllerAddSessionToMap>>, TError, Key, Arguments, Awaited<ReturnType<typeof sessionsControllerAddSessionToMap>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSessionsControllerAddSessionToMapMutationKey(id);
  const swrFn = getSessionsControllerAddSessionToMapMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить список доступных программ психолога
 */
export const psychologistControllerListPrograms = (
    
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<void>(
    {url: `/api/v1/psychologist/programs`, method: 'GET'
    },
    options);
  }



export const getPsychologistControllerListProgramsKey = () => [`/api/v1/psychologist/programs`] as const;

export type PsychologistControllerListProgramsQueryResult = NonNullable<Awaited<ReturnType<typeof psychologistControllerListPrograms>>>
export type PsychologistControllerListProgramsQueryError = unknown

/**
 * @summary Получить список доступных программ психолога
 */
export const usePsychologistControllerListPrograms = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof psychologistControllerListPrograms>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getPsychologistControllerListProgramsKey() : null);
  const swrFn = () => psychologistControllerListPrograms(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить программу по имени
 */
export const psychologistControllerGetProgram = (
    programName: string,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<void>(
    {url: `/api/v1/psychologist/programs/${programName}`, method: 'GET'
    },
    options);
  }



export const getPsychologistControllerGetProgramKey = (programName: string,) => [`/api/v1/psychologist/programs/${programName}`] as const;

export type PsychologistControllerGetProgramQueryResult = NonNullable<Awaited<ReturnType<typeof psychologistControllerGetProgram>>>
export type PsychologistControllerGetProgramQueryError = unknown

/**
 * @summary Получить программу по имени
 */
export const usePsychologistControllerGetProgram = <TError = unknown>(
  programName: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof psychologistControllerGetProgram>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(programName)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getPsychologistControllerGetProgramKey(programName) : null);
  const swrFn = () => psychologistControllerGetProgram(programName, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить сообщения сессии с cursor pagination
 */
export const messagesControllerGetMessages = (
    sessionId: string,
    params?: MessagesControllerGetMessagesParams,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<MessagesResponseDto>(
    {url: `/api/v1/sessions/${sessionId}/messages`, method: 'GET',
        params
    },
    options);
  }



export const getMessagesControllerGetMessagesKey = (sessionId: string,
    params?: MessagesControllerGetMessagesParams,) => [`/api/v1/sessions/${sessionId}/messages`, ...(params ? [params]: [])] as const;

export type MessagesControllerGetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof messagesControllerGetMessages>>>
export type MessagesControllerGetMessagesQueryError = void | void

/**
 * @summary Получить сообщения сессии с cursor pagination
 */
export const useMessagesControllerGetMessages = <TError = void | void>(
  sessionId: string,
    params?: MessagesControllerGetMessagesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof messagesControllerGetMessages>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(sessionId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getMessagesControllerGetMessagesKey(sessionId,params) : null);
  const swrFn = () => messagesControllerGetMessages(sessionId,params, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Отправить сообщение в сессию
 */
export const messagesControllerCreateMessage = (
    sessionId: string,
    createMessageDto: CreateMessageDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<MessageDto>(
    {url: `/api/v1/sessions/${sessionId}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMessageDto
    },
    options);
  }



export const getMessagesControllerCreateMessageMutationFetcher = (sessionId: string, options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: CreateMessageDto }) => {
    return messagesControllerCreateMessage(sessionId, arg, options);
  }
}
export const getMessagesControllerCreateMessageMutationKey = (sessionId: string,) => [`/api/v1/sessions/${sessionId}/messages`] as const;

export type MessagesControllerCreateMessageMutationResult = NonNullable<Awaited<ReturnType<typeof messagesControllerCreateMessage>>>
export type MessagesControllerCreateMessageMutationError = void | void | void

/**
 * @summary Отправить сообщение в сессию
 */
export const useMessagesControllerCreateMessage = <TError = void | void | void>(
  sessionId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof messagesControllerCreateMessage>>, TError, Key, CreateMessageDto, Awaited<ReturnType<typeof messagesControllerCreateMessage>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getMessagesControllerCreateMessageMutationKey(sessionId);
  const swrFn = getMessagesControllerCreateMessageMutationFetcher(sessionId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Получить все записи нейрокарты пользователя
 */
export const eventMapControllerGetEventMap = (
    
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<EventMapResponseDto[]>(
    {url: `/api/v1/event-map`, method: 'GET'
    },
    options);
  }



export const getEventMapControllerGetEventMapKey = () => [`/api/v1/event-map`] as const;

export type EventMapControllerGetEventMapQueryResult = NonNullable<Awaited<ReturnType<typeof eventMapControllerGetEventMap>>>
export type EventMapControllerGetEventMapQueryError = unknown

/**
 * @summary Получить все записи нейрокарты пользователя
 */
export const useEventMapControllerGetEventMap = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof eventMapControllerGetEventMap>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof swrMutator> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getEventMapControllerGetEventMapKey() : null);
  const swrFn = () => eventMapControllerGetEventMap(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * @summary Создать запись в нейрокарте
 */
export const eventMapControllerCreateEventMap = (
    createEventMapDto: CreateEventMapDto,
 options?: SecondParameter<typeof swrMutator>) => {
    return swrMutator<EventMapResponseDto>(
    {url: `/api/v1/event-map`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventMapDto
    },
    options);
  }



export const getEventMapControllerCreateEventMapMutationFetcher = ( options?: SecondParameter<typeof swrMutator>) => {
  return (_: Key, { arg }: { arg: CreateEventMapDto }) => {
    return eventMapControllerCreateEventMap(arg, options);
  }
}
export const getEventMapControllerCreateEventMapMutationKey = () => [`/api/v1/event-map`] as const;

export type EventMapControllerCreateEventMapMutationResult = NonNullable<Awaited<ReturnType<typeof eventMapControllerCreateEventMap>>>
export type EventMapControllerCreateEventMapMutationError = unknown

/**
 * @summary Создать запись в нейрокарте
 */
export const useEventMapControllerCreateEventMap = <TError = unknown>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof eventMapControllerCreateEventMap>>, TError, Key, CreateEventMapDto, Awaited<ReturnType<typeof eventMapControllerCreateEventMap>>> & { swrKey?: string }, request?: SecondParameter<typeof swrMutator>}
) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEventMapControllerCreateEventMapMutationKey();
  const swrFn = getEventMapControllerCreateEventMapMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
