/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import type { UserProfileDto } from './userProfileDto';

export interface AuthResponseDto {
  /** Access token */
  accessToken: string;
  /** Refresh token */
  refreshToken: string;
  /** Данные пользователя */
  user: UserProfileDto;
}
