/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface CreateSessionDto {
  /** Название сессии */
  title?: string;
  /** Название программы психолога */
  programName?: string;
}
