/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface CreateEventMapDto {
  /** Номер события */
  eventNumber: number;
  /** Описание события */
  event: string;
  /** Эмоция, вызванная событием */
  emotion: string;
  /** Идея/мысль, связанная с событием */
  idea: string;
  /** Корневое убеждение */
  rootBelief?: string;
}
