/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface EventMapResponseDto {
  /** ID записи */
  id: string;
  /** ID пользователя */
  userId: string;
  /** Номер события */
  eventNumber: number;
  /** Описание события */
  event: string;
  /** Эмоция */
  emotion: string;
  /** Идея */
  idea: string;
  /** Корневое убеждение */
  rootBelief?: string;
  /** Завершена ли обработка */
  isCompleted: boolean;
  /** Дата создания */
  createdAt: string;
  /** Дата обновления */
  updatedAt: string;
}
