/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

/**
 * Роль отправителя
 */
export type MessageDtoRole = typeof MessageDtoRole[keyof typeof MessageDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageDtoRole = {
  user: 'user',
  assistant: 'assistant',
} as const;
