/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import type { MessageDto } from './messageDto';

export interface MessagesResponseDto {
  /** Список сообщений */
  messages: MessageDto[];
  /**
   * Cursor для следующей страницы (ID последнего сообщения)
   * @nullable
   */
  nextCursor: string | null;
  /** Есть ли еще сообщения для загрузки */
  hasMore: boolean;
}
