/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import type { MessageDtoRole } from './messageDtoRole';

export interface MessageDto {
  /** ID сообщения */
  id: string;
  /** Роль отправителя */
  role: MessageDtoRole;
  /** Содержимое сообщения */
  content: string;
  /** Время отправки */
  timestamp: string;
}
