/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export type MessagesControllerGetMessagesParams = {
/**
 * Cursor для пагинации (ID последнего сообщения)
 */
cursor?: string;
/**
 * Количество сообщений (по умолчанию 50)
 */
limit?: number;
};
