/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */
import type { PurchaseSubscriptionDtoPlanId } from './purchaseSubscriptionDtoPlanId';
import type { PurchaseSubscriptionDtoPaymentMethod } from './purchaseSubscriptionDtoPaymentMethod';

export interface PurchaseSubscriptionDto {
  /** ID плана подписки */
  planId: PurchaseSubscriptionDtoPlanId;
  /** Промокод (опционально) */
  promoCode?: string;
  /** Способ оплаты */
  paymentMethod: PurchaseSubscriptionDtoPaymentMethod;
}
