/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

/**
 * ID плана подписки
 */
export type PurchaseSubscriptionDtoPlanId = typeof PurchaseSubscriptionDtoPlanId[keyof typeof PurchaseSubscriptionDtoPlanId];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PurchaseSubscriptionDtoPlanId = {
  monthly: 'monthly',
  quarterly: 'quarterly',
  yearly: 'yearly',
} as const;
