/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

/**
 * Способ оплаты
 */
export type PurchaseSubscriptionDtoPaymentMethod = typeof PurchaseSubscriptionDtoPaymentMethod[keyof typeof PurchaseSubscriptionDtoPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PurchaseSubscriptionDtoPaymentMethod = {
  card: 'card',
  yookassa: 'yookassa',
  balance: 'balance',
} as const;
