/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** Имя пользователя */
  username: string;
  /** Email пользователя */
  email: string;
  /**
   * Пароль
   * @minLength 6
   */
  password: string;
  /** Полное имя */
  name?: string;
}
