/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface SessionResponseDto {
  /** ID сессии */
  id: string;
  /** ID пользователя */
  userId: string;
  /**
   * Название сессии
   * @nullable
   */
  title: string | null;
  /** Количество сообщений */
  messageCount: number;
  /** Дата создания */
  createdAt: string;
  /** Дата обновления */
  updatedAt: string;
}
