/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface SubscriptionResponseDto {
  /** ID подписки */
  id: string;
  /** План подписки */
  plan: string;
  /** Статус подписки */
  status: string;
  /** Дата истечения */
  expiresAt: string;
  /** Автопродление */
  autoRenew: boolean;
}
