/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface TelegramLoginDto {
  /** Уникальный идентификатор пользователя в Telegram */
  id: string;
  /** Имя пользователя в Telegram */
  first_name: string;
  /** Фамилия пользователя в Telegram */
  last_name?: string;
  /** Username пользователя в Telegram */
  username?: string;
  /** URL аватара пользователя */
  photo_url?: string;
  /** Время авторизации (unix timestamp) */
  auth_date: number;
  /** Хэш, подписанный Telegram */
  hash: string;
}
