/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface UserProfileDto {
  /** ID пользователя */
  id: string;
  /** Имя пользователя */
  username: string;
  /** Email */
  email?: string;
  /** Полное имя */
  fullName?: string;
  /** URL аватара */
  avatarUrl?: string;
  /** Роль пользователя */
  role?: string;
  /** Тип аккаунта */
  accountType?: "USER" | "MANAGER" | "TEAM_MEMBER";
  /** Telegram ID (если привязан) */
  telegramId?: string | null;
  /** Публичный уникальный ID пользователя */
  userId?: string | null;
  /** Статус подписки */
  subscriptionStatus?: "NONE" | "ACTIVE" | "CANCELED";
  /** Активна ли подписка */
  subscriptionActive?: boolean;
  /** Дата окончания подписки */
  subscriptionEndsAt?: string | null;
  /** Сколько минут в день пользователь хочет тратить на приложение */
  dailyPracticeMinutes?: 5 | 10 | 15 | null;
  /** Текущий баланс монет */
  balance?: number;
  /** Серия дней подряд с закрытой ежедневной целью */
  dailyStreak?: number;
}
