/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SEEE API
 * API для системы AI-психолога
 * OpenAPI spec version: 1.0
 */

export interface UserProfileDto {
  /** ID пользователя */
  id: string;
  /** Имя пользователя */
  username: string;
  /** Email */
  email?: string;
  /** Полное имя */
  fullName?: string;
  /** URL аватара */
  avatarUrl?: string;
  /** Telegram ID (если привязан) */
  telegramId?: string | null;
}
