# Dockerfile для development режима
FROM node:22.21.0-alpine

WORKDIR /app

# Копируем package файлы
COPY package*.json ./

# Устанавливаем все зависимости (включая dev)
RUN npm i

# Копируем конфигурационные файлы
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.node.json ./
COPY tailwind.config.js ./
COPY postcss.config.js ./
COPY index.html ./
COPY components.json ./

# Устанавливаем wget для healthcheck
RUN apk add --no-cache wget

# По умолчанию запускаем dev сервер
CMD ["npm", "run", "dev", "--", "--host"]

